### ISSUE TITLE
No sound and no sprites in all MCR3 games

### ISSUE THREAD

**Issue by skooterblog** [MiSTer-devel/Arcade-MCR3_MiSTer#3]
I don't know if this is a rare bug or if my De10Nano is defective, but all my MCR3 games and MCR Monoboard games have no sound and the sprites do not show.

I already tried getting the ROMs from different sources and downloading cores again, nothing helped.

 I don't have SDRAM yet. Other arcades and console cores (which don't use SDRAM) are working fine.

Here is a video showing the problem:
https://www.youtube.com/watch?v=ToIBEDSCWvY

**Comment by sorgelig** [comment]
MCR3/Mono require SDRAM

**Comment by skooterblog** [comment]
Thank you. I thought it could be SDRAM, but the other SDRAM cores I tried wouldn't work at all, so it was weird that those ones were partially working. Moreover, I read somewhere that the Arcade cores didn't need it.

My suggestion is to include information about SDRAM requirements in the README.md of the cores which need it.
